version: '3'
services:
    mongo-db-server:
        image: mongo
        ports:
            - '27017:27017'
    server:
        build: ./server
        ports:
            - '4000:4000'
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment:
            - NODE_ENV=production
            - MONGO_DB_NAME=testdb
        depends_on:
            - mongo-db-server
    client:
        build: ./client
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        volumes:
            - '.:/app'
            - '/app/node_modules'
        depends_on:
            - server
